In [2]:
import numpy as np

# Create a constant array
a = np.full((2, 2), 7.0)

print(a)

[[7. 7.]
 [7. 7.]]


In [3]:
# Create an array filled with random values
a = np.random.rand(2, 2)

print(a)

[[0.08819531 0.93854606]
 [0.64067918 0.26926672]]


In [4]:
# Create an array containing numbers from 10 to 50
a = np.arange(10, 51)

print("Array:")
print(a)

print("\nNumber of elements:")
print(a.size)

print("\nShape:")
print(a.shape)

print("\nDimension:")
print(a.ndim)

print("\nData type:")
print(a.dtype)

Array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

Number of elements:
41

Shape:
(41,)

Dimension:
1

Data type:
int64


In [5]:
# 1D array containing 10 zeros
zeros = np.zeros(10)

# 3 x 3 array containing ones
ones = np.ones((3, 3))

# 4 x 4 identity matrix
identity = np.eye(4)

# Numbers from 5 to 50 with step size 5
numbers = np.arange(5, 51, 5)

print("10 zeros:")
print(zeros)

print("\n3 x 3 ones:")
print(ones)

print("\n4 x 4 identity matrix:")
print(identity)

print("\nNumbers from 5 to 50:")
print(numbers)

10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

3 x 3 ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

4 x 4 identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Numbers from 5 to 50:
[ 5 10 15 20 25 30 35 40 45 50]


In [6]:
# Create array containing numbers from 1 to 24
a = np.arange(1, 25)

# Reshape into 4 x 6
a_4x6 = a.reshape(4, 6)

# Reshape into 6 x 4
a_6x4 = a.reshape(6, 4)

# Reshape into 2 x 3 x 4
a_2x3x4 = a.reshape(2, 3, 4)

print("4 x 6:")
print(a_4x6)
print("Shape:", a_4x6.shape)
print("ndim:", a_4x6.ndim)

print("\n6 x 4:")
print(a_6x4)
print("Shape:", a_6x4.shape)
print("ndim:", a_6x4.ndim)

print("\n2 x 3 x 4:")
print(a_2x3x4)
print("Shape:", a_2x3x4.shape)
print("ndim:", a_2x3x4.ndim)

4 x 6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)
ndim: 2

6 x 4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)
ndim: 2

2 x 3 x 4:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
ndim: 3


In [7]:
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

print("First element:")
print(marks[0])

print("\nLast element:")
print(marks[-1])

print("\nThird element:")
print(marks[2])

print("\nFirst four elements:")
print(marks[:4])

print("\nLast three elements:")
print(marks[-3:])

First element:
78

Last element:
81

Third element:
92

First four elements:
[78 85 92 67]

Last three elements:
[73 95 81]


In [8]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

print("a + b:")
print(a + b)

print("\na - b:")
print(a - b)

print("\na * b:")
print(a * b)

print("\na / b:")
print(a / b)

print("\nSquare of every element in a:")
print(a ** 2)

a + b:
[15 30 45 60 75]

a - b:
[ 5 10 15 20 25]

a * b:
[  50  200  450  800 1250]

a / b:
[2. 2. 2. 2. 2.]

Square of every element in a:
[ 100  400  900 1600 2500]


In [9]:
salary = np.array([
    25000, 32000, 28000, 45000,
    50000, 38000, 42000, 30000
])

print("Total salary:")
print(np.sum(salary))

print("\nAverage salary:")
print(np.mean(salary))

print("\nHighest salary:")
print(np.max(salary))

print("\nLowest salary:")
print(np.min(salary))

print("\nMedian salary:")
print(np.median(salary))

print("\nStandard deviation:")
print(np.std(salary))

Total salary:
290000

Average salary:
36250.0

Highest salary:
50000

Lowest salary:
25000

Median salary:
35000.0

Standard deviation:
8317.902379807063


In [10]:
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

print("Marks greater than 75:")
print(marks[marks > 75])

print("\nMarks between 50 and 80:")
print(marks[(marks >= 50) & (marks <= 80)])

print("\nNumber of students who scored below 50:")
print(np.sum(marks < 50))

print("\nPercentage of students who scored 60 or above:")
percentage = np.mean(marks >= 60) * 100
print(percentage)

Marks greater than 75:
[78 89 90 76 84]

Marks between 50 and 80:
[78 67 55 76]

Number of students who scored below 50:
3

Percentage of students who scored 60 or above:
60.0


In [11]:
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

print("Total marks of each student:")
print(np.sum(marks, axis=1))

print("\nAverage marks of each student:")
print(np.mean(marks, axis=1))

print("\nAverage marks in each subject:")
print(np.mean(marks, axis=0))

print("\nStudent with the highest total:")
totals = np.sum(marks, axis=1)
print(np.argmax(totals) + 1)

print("\nHighest mark in each subject:")
print(np.max(marks, axis=0))

Total marks of each student:
[245 207 265 173]

Average marks of each student:
[81.66666667 69.         88.33333333 57.66666667]

Average marks in each subject:
[72.   74.25 76.25]

Student with the highest total:
3

Highest mark in each subject:
[88 92 90]


In [12]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix addition:")
print(A + B)

print("\nElement-wise multiplication:")
print(A * B)

print("\nMatrix multiplication:")
print(A @ B)

print("\nTranspose of A:")
print(A.T)

Matrix addition:
[[ 6  8]
 [10 12]]

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]


In [13]:
# A * B performs element-wise multiplication.
# A @ B performs matrix multiplication.

print("A * B:")
print(A * B)

print("\nA @ B:")
print(A @ B)

A * B:
[[ 5 12]
 [21 32]]

A @ B:
[[19 22]
 [43 50]]


In [14]:
temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

average = np.mean(temperature)

print("Mean temperature:")
print(average)

print("\nMaximum temperature:")
print(np.max(temperature))

print("\nMinimum temperature:")
print(np.min(temperature))

print("\nNumber of days above average:")
print(np.sum(temperature > average))

print("\nTemperatures greater than 34°C:")
print(temperature[temperature > 34])

print("\nDifference between maximum and minimum:")
print(np.max(temperature) - np.min(temperature))

print("\nStandard deviation:")
print(np.std(temperature))

Mean temperature:
33.142857142857146

Maximum temperature:
37

Minimum temperature:
29

Number of days above average:
6

Temperatures greater than 34°C:
[35 36 35 37 36]

Difference between maximum and minimum:
8

Standard deviation:
2.356060357495806


In [15]:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

print("Total annual sales:")
print(np.sum(sales))

print("\nAverage monthly sales:")
print(np.mean(sales))

print("\nMonth with highest sales:")
print(np.argmax(sales) + 1)

print("\nMonth with lowest sales:")
print(np.argmin(sales) + 1)

print("\nNumber of months with sales above ₹20,000:")
print(np.sum(sales > 20000))

print("\nPercentage increase from January to December:")
increase = ((sales[-1] - sales[0]) / sales[0]) * 100
print(increase, "%")

Total annual sales:
240000

Average monthly sales:
20000.0

Month with highest sales:
12

Month with lowest sales:
1

Number of months with sales above ₹20,000:
6

Percentage increase from January to December:
133.33333333333331 %


In [16]:
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

totals = np.sum(marks, axis=1)
averages = np.mean(marks, axis=1)
subject_average = np.mean(marks, axis=0)

print("Total marks of every student:")
print(totals)

print("\nAverage of every student:")
print(averages)

print("\nAverage mark for every subject:")
print(subject_average)

print("\nHighest-scoring student:")
print(np.argmax(totals) + 1)

print("\nLowest-scoring student:")
print(np.argmin(totals) + 1)

print("\nStudents whose average is greater than 80:")
print(np.where(averages > 80)[0] + 1)

print("\nOverall class average:")
print(np.mean(marks))

Total marks of every student:
[341 275 366 235 316]

Average of every student:
[85.25 68.75 91.5  58.75 79.  ]

Average mark for every subject:
[74.  75.6 79.4 77.6]

Highest-scoring student:
3

Lowest-scoring student:
4

Students whose average is greater than 80:
[1 3]

Overall class average:
76.65


In [17]:
# Generate 20 random integers between 1 and 100
random_numbers = np.random.randint(1, 101, 20)

print(random_numbers)

[78 28 17 65 41 14 69 41 37 85 32 85 25 83 29 40 64 25 36  2]


In [18]:
# Find all even numbers
even_numbers = random_numbers[random_numbers % 2 == 0]

print("Even numbers:")
print(even_numbers)

Even numbers:
[78 28 14 32 40 64 36  2]


In [19]:
# Replace values below 50 with 0
result = np.where(random_numbers < 50, 0, random_numbers)

print("Original array:")
print(random_numbers)

print("\nAfter replacing values below 50:")
print(result)

Original array:
[78 28 17 65 41 14 69 41 37 85 32 85 25 83 29 40 64 25 36  2]

After replacing values below 50:
[78  0  0 65  0  0 69  0  0 85  0 85  0 83  0  0 64  0  0  0]


In [20]:
print("Ascending order:")
print(np.sort(random_numbers))

print("\nDescending order:")
print(np.sort(random_numbers)[::-1])

Ascending order:
[ 2 14 17 25 25 28 29 32 36 37 40 41 41 64 65 69 78 83 85 85]

Descending order:
[85 85 83 78 69 65 64 41 41 40 37 36 32 29 28 25 25 17 14  2]


In [21]:
unique_values, frequencies = np.unique(
    random_numbers,
    return_counts=True
)

print("Unique values:")
print(unique_values)

print("\nFrequencies:")
print(frequencies)

Unique values:
[ 2 14 17 25 28 29 32 36 37 40 41 64 65 69 78 83 85]

Frequencies:
[1 1 1 2 1 1 1 1 1 1 2 1 1 1 1 1 2]


In [22]:
# Create a 5 x 5 random matrix
matrix = np.random.randint(1, 101, (5, 5))

print("Random 5 x 5 matrix:")
print(matrix)

print("\nRow-wise means:")
print(np.mean(matrix, axis=1))

print("\nColumn-wise means:")
print(np.mean(matrix, axis=0))

Random 5 x 5 matrix:
[[28 83 95 31 25]
 [12 83 62 61  7]
 [34  1 16 73 98]
 [44 56 46 95 57]
 [75 31  5 78 10]]

Row-wise means:
[52.4 45.  44.4 59.6 39.8]

Column-wise means:
[38.6 50.8 44.8 67.6 39.4]


In [23]:
# Example array
a = np.array([10, 20, 30, 40, 50])

# Min-Max normalization
normalized = (a - np.min(a)) / (np.max(a) - np.min(a))

print("Original array:")
print(a)

print("\nNormalized array:")
print(normalized)

Original array:
[10 20 30 40 50]

Normalized array:
[0.   0.25 0.5  0.75 1.  ]


In [24]:
# Example data
a = np.array([10, 20, 30, 40, 50])

# Standardization
standardized = (a - np.mean(a)) / np.std(a)

print("Original array:")
print(a)

print("\nStandardized array:")
print(standardized)

Original array:
[10 20 30 40 50]

Standardized array:
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [25]:
# Generate 100 random exam marks between 0 and 100
marks = np.random.randint(0, 101, 100)

print("Number of students in 0–39:")
print(np.sum((marks >= 0) & (marks <= 39)))

print("\nNumber of students in 40–59:")
print(np.sum((marks >= 40) & (marks <= 59)))

print("\nNumber of students in 60–79:")
print(np.sum((marks >= 60) & (marks <= 79)))

print("\nNumber of students in 80–100:")
print(np.sum((marks >= 80) & (marks <= 100)))

Number of students in 0–39:
41

Number of students in 40–59:
15

Number of students in 60–79:
20

Number of students in 80–100:
24


In [26]:
import time

# Create 1,000,000 numbers
list1 = list(range(1000000))
list2 = list(range(1000000))

array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Python list multiplication
start = time.time()

list_result = [a * b for a, b in zip(list1, list2)]

list_time = time.time() - start

# NumPy array multiplication
start = time.time()

array_result = array1 * array2

numpy_time = time.time() - start

print("Time using Python list:")
print(list_time, "seconds")

print("\nTime using NumPy array:")
print(numpy_time, "seconds")

Time using Python list:
0.03897905349731445 seconds

Time using NumPy array:
0.002005338668823242 seconds
